# Generated by Django 2.1.15 on 2020-11-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_reg_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='media/img'),
        ),
    ]
