# Generated by Django 2.1.15 on 2020-11-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_auto_20201112_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
