# Generated by Django 2.1.15 on 2020-11-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0009_auto_20201112_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('audio', models.FileField(blank=True, upload_to='static/audio')),
            ],
        ),
    ]
