# Generated by Django 2.1.15 on 2020-11-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0010_word'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Word',
        ),
    ]
