# Generated by Django 3.1.3 on 2020-11-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0011_delete_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='person',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
